name: CI Workflow

on:
  push:
    branches:
      - main  # Dispara el workflow cuando se hace un push a la rama 'main'
  pull_request:
    branches:
      - main  # Dispara el workflow cuando se crea una PR hacia la rama 'main'

jobs:
  build:
    runs-on: ubuntu-latest  # Utilizamos un entorno Ubuntu

    steps:
    # Paso 1: Checkout del código
    - name: Checkout code
      uses: actions/checkout@v2  # Clona el repositorio

    # Paso 2: Configurar Python 3.11
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  # Especifica la versión de Python que deseas usar

    # Paso 3: Instalar dependencias del proyecto
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip  # Actualiza pip
        pip install -r requirements.txt  # Instala las dependencias desde el archivo requirements.txt

    # Paso 4: Ejecutar el script de Python
    - name: Run Python script
      run: |
        python tests/test.py  # Reemplaza 'my_script.py' con el nombre de tu script
      continue-on-error: false